spring.datasource.url=jdbc:mysql://localhost:3306/usermanagedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=db_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
